name: Build python-ldap wheels for Windows using MSYS
on:
  workflow_dispatch:
    inputs:
      release_title:
        description: 'Release title'
        required: true
      python_ldap_version:
        description: 'python-ldap version'
        required: true
        default: '3.4.4'
env:
  PYTHONLDAP_VER: python-ldap-${{ github.event.inputs.python_ldap_version }}
  TITLE: ${{ github.event.inputs.release_title }}
  TAG: ${{ github.event.inputs.python_ldap_version }}+MSYS
jobs:
  build-msys2-ucrt64:
    name: Build UCRT64 wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: type python; python -V
        shell: bash
      # https://www.msys2.org/docs/ci/
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-openldap
          #mingw-w64-x86_64-python mingw-w64-x86_64-python-setuptools
      - run: |
          set -ex
          pwd
          env
          curl -L -o "$PYTHONLDAP_VER.tar.gz" "https://github.com/python-ldap/python-ldap/archive/refs/tags/$PYTHONLDAP_VER.tar.gz"
          tar -xf "$PYTHONLDAP_VER.tar.gz" --strip-components=1
          $pythonLocation/python -m pip install setuptools || :
          $pythonLocation/python setup.py bdist_wheel # python_ldap-3.4.4-cp312-cp312-mingw_x86_64_msvcrt_gnu.whl
        shell: msys2 {0}
      - run: gh release create --draft --title "$TITLE" "$TAG" dist/*.whl
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
